// Single source of truth for all entity type definitions.
// Drives export, import, conflict detection, and validation generically.

const ENTITY_CONFIG = {
  status_effects: {
    table: 'status_effect_definitions',
    exportKey: 'status_effects',
    displayName: 'Status Effects',
    nameField: 'name',
    columns: [
      { name: 'name',           type: 'text',    default: '' },
      { name: 'description',    type: 'text',    default: '' },
      { name: 'tags',           type: 'json',    default: [] },
      { name: 'modifiers',      type: 'json',    default: [] },
      { name: 'duration_type',  type: 'text',    default: 'indefinite' },
      { name: 'duration_value', type: 'integer', default: 0 },
    ],
    modifierColumns: ['modifiers'],
    idMapKey: 'effectIdMap',
    relations: [],
  },
  items: {
    table: 'item_definitions',
    exportKey: 'items',
    displayName: 'Items',
    nameField: 'name',
    columns: [
      { name: 'name',        type: 'text',     default: '' },
      { name: 'description', type: 'text',     default: '' },
      { name: 'item_type',   type: 'text',     default: 'misc' },
      { name: 'properties',  type: 'json',     default: {} },
      { name: 'stackable',   type: 'bool_int', default: false },
      { name: 'modifiers',   type: 'json',     default: [] },
    ],
    modifierColumns: ['modifiers'],
    idMapKey: 'itemIdMap',
    relations: [],
  },
  characters: {
    table: 'characters',
    exportKey: 'characters',
    displayName: 'Characters',
    nameField: 'name',
    columns: [
      { name: 'name',            type: 'text', default: '' },
      { name: 'type',            type: 'text', default: 'NPC' },
      { name: 'description',     type: 'text', default: '' },
      { name: 'portrait_url',    type: 'text', default: '' },
      { name: 'base_attributes', type: 'json', default: {} },
      { name: 'max_attributes',  type: 'json', default: {} },
      { name: 'dm_notes',        type: 'text', default: '' },
      { name: 'spawned_from_encounter_id', type: 'integer', default: null },
      { name: 'archived', type: 'bool_int', default: false },
    ],
    modifierColumns: [],
    idMapKey: 'charIdMap',
    relations: [
      {
        table: 'applied_effects',
        foreignKey: 'character_id',
        otherForeignKey: 'status_effect_definition_id',
        otherIdMapKey: 'effectIdMap',
        exportKey: 'applied_effects',
        columns: [
          { name: 'applied_at',       type: 'text',    default: null },
          { name: 'remaining_rounds', type: 'integer', default: null },
          { name: 'remaining_hours',  type: 'real',    default: null },
        ],
      },
      {
        table: 'character_items',
        foreignKey: 'character_id',
        otherForeignKey: 'item_definition_id',
        otherIdMapKey: 'itemIdMap',
        exportKey: 'character_items',
        columns: [
          { name: 'quantity', type: 'integer', default: 1 },
        ],
      },
    ],
  },
  encounters: {
    table: 'encounter_definitions',
    exportKey: 'encounters',
    displayName: 'Encounters',
    nameField: 'name',
    columns: [
      { name: 'name',                  type: 'text', default: '' },
      { name: 'description',           type: 'text', default: '' },
      { name: 'notes',                 type: 'text', default: '' },
      { name: 'npcs',                  type: 'json', default: [] },
      { name: 'environment_overrides', type: 'json', default: {} },
      { name: 'loot_table',            type: 'json', default: [] },
      { name: 'conditions',            type: 'json', default: {} },
      { name: 'starts_combat',         type: 'bool_int', default: false },
    ],
    modifierColumns: [],
    idMapKey: 'encounterIdMap',
    relations: [],
    postProcess: 'remapEncounterNpcs',
  },
  locations: {
    table: 'locations',
    exportKey: 'locations',
    displayName: 'Locations',
    nameField: 'name',
    columns: [
      { name: 'name',               type: 'text',    default: '' },
      { name: 'description',        type: 'text',    default: '' },
      { name: 'parent_id',          type: 'integer', default: null },
      { name: 'weather_override',   type: 'json',    default: null },
      { name: 'encounter_modifier', type: 'real',    default: 1.0 },
      { name: 'properties',         type: 'json',    default: {} },
      { name: 'position_x',         type: 'real',    default: 0 },
      { name: 'position_y',         type: 'real',    default: 0 },
    ],
    modifierColumns: [],
    idMapKey: 'locationIdMap',
    relations: [],
    postProcess: 'remapLocationEdges',
  },
  journal_notes: {
    table: 'journal_notes',
    exportKey: 'journal_notes',
    displayName: 'Journal Notes',
    nameField: 'title',
    columns: [
      { name: 'title',      type: 'text',     default: '' },
      { name: 'content',    type: 'text',     default: '' },
      { name: 'tags',       type: 'json',     default: [] },
      { name: 'starred',    type: 'bool_int', default: false },
      { name: 'created_at', type: 'text',     default: null },
      { name: 'updated_at', type: 'text',     default: null },
    ],
    modifierColumns: [],
    idMapKey: 'journalIdMap',
    relations: [],
  },
  random_tables: {
    table: 'random_tables',
    exportKey: 'random_tables',
    displayName: 'Random Tables',
    nameField: 'name',
    columns: [
      { name: 'name',        type: 'text', default: '' },
      { name: 'description', type: 'text', default: '' },
      { name: 'table_type',  type: 'text', default: 'weighted' },
      { name: 'entries',     type: 'json', default: [] },
      { name: 'created_at',  type: 'text', default: null },
    ],
    modifierColumns: [],
    idMapKey: 'randomTableIdMap',
    relations: [],
  },
  rules: {
    table: 'rule_definitions',
    exportKey: 'rules',
    displayName: 'Rules',
    nameField: 'name',
    columns: [
      { name: 'name',           type: 'text',    default: '' },
      { name: 'description',    type: 'text',    default: '' },
      { name: 'enabled',        type: 'bool_int', default: true },
      { name: 'trigger_type',   type: 'text',    default: 'on_time_advance' },
      { name: 'trigger_config', type: 'json',    default: {} },
      { name: 'conditions',     type: 'json',    default: { all: [] } },
      { name: 'actions',        type: 'json',    default: [] },
      { name: 'action_mode',    type: 'text',    default: 'auto' },
      { name: 'priority',       type: 'integer', default: 100 },
      { name: 'tags',           type: 'json',    default: [] },
      { name: 'target_mode',    type: 'text',    default: 'environment' },
      { name: 'target_config',  type: 'json',    default: {} },
    ],
    modifierColumns: [],
    idMapKey: 'ruleIdMap',
    relations: [],
  },
};

// Order matters: effects and items before characters (for relation ID mapping),
// locations before encounters (encounter conditions reference location IDs),
// encounters last (needs charIdMap for NPC remapping).
// rules last — they're standalone, no cross-references.
const IMPORT_ORDER = ['status_effects', 'items', 'characters', 'locations', 'encounters', 'rules', 'random_tables', 'journal_notes'];

module.exports = { ENTITY_CONFIG, IMPORT_ORDER };
